# Generated by Django 4.2.6 on 2023-11-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginRegistroUsuario', '0003_alter_barbero_table_alter_cliente_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('hora_agendada', models.DateTimeField(verbose_name='Fecha agendada')),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=8)),
                ('id_barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginRegistroUsuario.barbero')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginRegistroUsuario.cliente')),
            ],
            options={
                'db_table': 'Cita',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_pago', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'MetodoPago',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=45)),
                ('descripcion', models.TextField(max_length=150)),
                ('precio', models.IntegerField()),
                ('stock', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=150)),
                ('duracion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('id_metodo_pago', models.IntegerField()),
                ('hora_fecha', models.TimeField()),
                ('total', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.venta')),
            ],
            options={
                'db_table': 'ProductoVenta',
            },
        ),
        migrations.CreateModel(
            name='CitaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cita')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.venta')),
            ],
            options={
                'db_table': 'CitaVenta',
            },
        ),
        migrations.CreateModel(
            name='CitaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cita')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.servicio')),
            ],
            options={
                'db_table': 'CitaServicio',
            },
        ),
    ]
