# Generated by Django 4.2.6 on 2023-11-19 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistroUsuario', '0004_alter_barbero_id_usuario_alter_cliente_id_usuario_and_more'),
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id_barbero',
            field=models.ForeignKey(db_column='fk_id_barbero', on_delete=django.db.models.deletion.CASCADE, to='loginRegistroUsuario.barbero'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_cliente',
            field=models.ForeignKey(db_column='fk_id_cliente', on_delete=django.db.models.deletion.CASCADE, to='loginRegistroUsuario.cliente'),
        ),
        migrations.AlterField(
            model_name='citaservicio',
            name='id_cita',
            field=models.ForeignKey(db_column='fk_id_cita', on_delete=django.db.models.deletion.CASCADE, to='intranet.cita'),
        ),
        migrations.AlterField(
            model_name='citaservicio',
            name='id_servicio',
            field=models.ForeignKey(db_column='fk_id_servicio', on_delete=django.db.models.deletion.CASCADE, to='intranet.servicio'),
        ),
        migrations.AlterField(
            model_name='citaventa',
            name='id_cita',
            field=models.ForeignKey(db_column='fk_id_cita', on_delete=django.db.models.deletion.CASCADE, to='intranet.cita'),
        ),
        migrations.AlterField(
            model_name='citaventa',
            name='id_venta',
            field=models.ForeignKey(db_column='fk_id_venta', on_delete=django.db.models.deletion.CASCADE, to='intranet.venta'),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='id_producto',
            field=models.ForeignKey(db_column='fk_id_producto', on_delete=django.db.models.deletion.CASCADE, to='intranet.producto'),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='id_venta',
            field=models.ForeignKey(db_column='fk_id_venta', on_delete=django.db.models.deletion.CASCADE, to='intranet.venta'),
        ),
    ]
