# Generated by Django 4.2.6 on 2023-10-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.IntegerField(max_length=1, primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=90)),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginRegistroUsuario.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=120)),
                ('apellido_paterno', models.CharField(max_length=120)),
                ('apellido_materno', models.CharField(max_length=120)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario'), ('O', 'Otro'), ('PND', 'Prefiero no decirlo')], default='M', max_length=3)),
                ('numero_telefonico', models.CharField(max_length=45)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginRegistroUsuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id_barbero', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=10)),
                ('nombres', models.CharField(max_length=120)),
                ('apellido_paterno', models.CharField(max_length=120)),
                ('apellido_materno', models.CharField(max_length=120)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario'), ('O', 'Otro'), ('PND', 'Prefiero no decirlo')], default='M', max_length=3)),
                ('numero_telefonico', models.CharField(max_length=45)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginRegistroUsuario.usuario')),
            ],
        ),
    ]
