# Generated by Django 4.2.6 on 2023-10-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistroUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='id_tipo_usuario',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
