# Generated by Django 4.2.6 on 2023-11-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistroUsuario', '0002_alter_tipousuario_id_tipo_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barbero',
            table='Barbero',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
        migrations.AlterModelTable(
            name='tipousuario',
            table='TipoUsuario',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
