# Generated by Django 4.2.6 on 2023-11-19 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistroUsuario', '0003_alter_barbero_table_alter_cliente_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbero',
            name='id_usuario',
            field=models.ForeignKey(db_column='fk_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='loginRegistroUsuario.usuario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_usuario',
            field=models.ForeignKey(db_column='fk_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='loginRegistroUsuario.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_tipo_usuario',
            field=models.ForeignKey(db_column='fk_id_tipo_usuario', on_delete=django.db.models.deletion.CASCADE, to='loginRegistroUsuario.tipousuario'),
        ),
    ]
