# Generated by Django 4.1.2 on 2023-12-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistroUsuario', '0004_alter_barbero_id_usuario_alter_cliente_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbero',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fk_id_tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loginRegistroUsuario.tipousuario'),
        ),
    ]
